using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using PTAData.Entities;

namespace HickoryPTAApp.Models
{ 
    public class CommitteeRepository : BaseRepository, ICommitteeRepository
    {
        HickoryPTAAppContext context = new HickoryPTAAppContext();

        public IQueryable<Committee> All
        {
            get { return context.Committees; }
        }

        public IQueryable<Committee> AllIncluding(params Expression<Func<Committee, object>>[] includeProperties)
        {
            IQueryable<Committee> query = context.Committees;
            foreach (var includeProperty in includeProperties) {
                query = query.Include(includeProperty);
            }
            return query;
        }

        public Committee Find(int id)
        {
            var committee = context.Committees.Find(id);
            if (committee.ChairPersons != null && committee.ChairPersons.Count > 1)
                committee.ChairPersons = committee.ChairPersons.OrderBy(c => c.Rank).ToList();

            return committee;
        }

        public void InsertOrUpdate(Committee committee, string currentUser)
        {
            committee.UpdateForeignKeys();
            if (committee.CommitteeId == default(int)) {
                // New entity
                UpdateAutoGeneratedFields(committee, currentUser, true);
                context.Committees.Add(committee);
            } else {
                // Existing entity
                UpdateAutoGeneratedFields(committee, currentUser, false);

                if (committee.ChairPersons != null)
                {
                    foreach (var chair in committee.ChairPersons)
                    {
                        if (context.CommitteeChairs.Any(c => c.CommitteeId == chair.CommitteeId && c.MemberId == chair.MemberId))
                            context.Entry(chair).State = System.Data.Entity.EntityState.Modified;
                        else
                            context.Entry(chair).State = System.Data.Entity.EntityState.Added;

                    }
                }

                if (committee.Posts != null)
                { 
                    foreach (var post in committee.Posts)
                    {
                        UpdatePost(post, currentUser);
                    }
                }

                if (committee.Events != null)
                {
                    foreach (var evt in committee.Events)
                    {
                        UpdateLocation(evt, currentUser);
                        UpdatePost(evt, currentUser);
                    }
                }

                UpdateAutoGeneratedFields(committee, currentUser, false);
                context.Entry(committee).State = System.Data.Entity.EntityState.Modified;
            }
        }

        public void RemoveChairPerson(ChairPerson chair)
        {
            context.Entry(chair).State = System.Data.Entity.EntityState.Deleted;
        }

        public void RemoveMemberFromCommittes(Member member)
        {
            var chairs = context.CommitteeChairs.Where(c => c.Member.MemberId == member.MemberId);
            chairs.ForEachAsync(RemoveChairPerson).Wait();
        }

        private void UpdateLocation(CommitteeEvent evt, string currentUser)
        {
            if (evt.Location == null)
                return; 

            var location = evt.Location;
            if (string.IsNullOrEmpty(location.Name) &&
                location.Address != null &&
                string.IsNullOrEmpty(location.Address.StreetAddress))
            {
                evt.Location = null;
                return;
            }

            if (location.LocationId == default(int))
            {
                context.Entry(location).State = System.Data.Entity.EntityState.Added;
            }
            else
            {
                context.Entry(location).State = System.Data.Entity.EntityState.Modified;
            }
        }

        private void UpdatePost(Post post, string currentUser)
        {
            if (post.PostId == default(int))
            {
                UpdateAutoGeneratedFields(post, currentUser, true);
                context.Entry(post).State = System.Data.Entity.EntityState.Added;
            }
            else
            {
                UpdateAutoGeneratedFields(post, currentUser, false);
                context.Entry(post).State = System.Data.Entity.EntityState.Modified;
            }
        }

        public void Delete(int id)
        {
            var committee = context.Committees.Find(id);
            context.Committees.Remove(committee);
        }

        public void Save()
        {
            context.SaveChanges();
        }

        public void Dispose() 
        {
            context.Dispose();
        }

        internal Committee GlobalPtaCommittee()
        {
            var globalPtaCommittee = All.FirstOrDefault(m => m.CommitteeName == "PTA");

            if (globalPtaCommittee == null)
            {
                globalPtaCommittee = new Committee()
                {
                    CommitteeName = "PTA",
                    Description = "Hickory Elementary PTA"
                };

                InsertOrUpdate(globalPtaCommittee, "Seed");
                Save();
            }

            return globalPtaCommittee;
        }

        internal Committee GlobalNewsletterCommittee()
        {
            var globalNewsletterCommittee = All.FirstOrDefault(m => m.CommitteeName.Contains("Newsletter"));            

            return globalNewsletterCommittee;
        }
    }

    public interface ICommitteeRepository : IDisposable
    {
        IQueryable<Committee> All { get; }
        IQueryable<Committee> AllIncluding(params Expression<Func<Committee, object>>[] includeProperties);
        Committee Find(int id);
        void InsertOrUpdate(Committee committee, string currentUser);
        void Delete(int id);
        void Save();

        void RemoveChairPerson(ChairPerson chair);
        void RemoveMemberFromCommittes(Member member);
    }
}