using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using PTAData.Entities;

namespace HickoryPTAApp.Models
{ 
    public class CommitteeRepository : ICommitteeRepository
    {
        HickoryPTAAppContext context = new HickoryPTAAppContext();

        public IQueryable<Committee> All
        {
            get { return context.Committees; }
        }

        public IQueryable<Committee> AllIncluding(params Expression<Func<Committee, object>>[] includeProperties)
        {
            IQueryable<Committee> query = context.Committees;
            foreach (var includeProperty in includeProperties) {
                query = query.Include(includeProperty);
            }
            return query;
        }

        public Committee Find(int id)
        {
            var committee = context.Committees.Find(id);            
            return committee;
        }

        public void InsertOrUpdate(Committee committee, string currentUser)
        {
            committee.UpdateForeignKeys();
            if (committee.CommitteeId == default(int)) {
                // New entity
                UpdateAutoGeneratedFields(committee, currentUser, true);
                context.Committees.Add(committee);
            } else {
                // Existing entity
                committee.LastModified = DateTime.Now;

                if (committee.ChairPersons != null)
                {
                    foreach (var chair in committee.ChairPersons)
                    {
                        if (context.CommitteeChairs.Any(c => c.CommitteeId == chair.CommitteeId && c.MemberId == chair.MemberId))
                            context.Entry(chair).State = System.Data.Entity.EntityState.Modified;
                        else
                            context.Entry(chair).State = System.Data.Entity.EntityState.Added;

                    }
                }

                if (committee.Posts != null)
                { 
                    foreach (var post in committee.Posts)
                    {
                        UpdatePost(post, currentUser);
                    }
                }

                if (committee.Events != null)
                {
                    foreach (var evt in committee.Events)
                    {
                        UpdatePost(evt, currentUser);
                    }
                }

                UpdateAutoGeneratedFields(committee, currentUser, false);
                context.Entry(committee).State = System.Data.Entity.EntityState.Modified;
            }
        }

        private void UpdatePost(Post post, string currentUser)
        {
            if (post.PostId == default(int))
            {
                UpdateAutoGeneratedFields(post, currentUser, true);
                context.Entry(post).State = System.Data.Entity.EntityState.Added;
            }
            else
            {
                UpdateAutoGeneratedFields(post, currentUser, false);
                context.Entry(post).State = System.Data.Entity.EntityState.Modified;
            }
        }

        private void UpdateAutoGeneratedFields(object obj, string user, bool newItem)
        {
            var item = obj as IAutoGenerateFields;

            if (item == null)
                return;

            if (newItem)
                item.CreatedOn = DateTime.Now;

            item.UserModified = user;
            item.LastModified = DateTime.Now;
        }

        public void Delete(int id)
        {
            var committee = context.Committees.Find(id);
            context.Committees.Remove(committee);
        }

        public void Save()
        {
            context.SaveChanges();
        }

        public void Dispose() 
        {
            context.Dispose();
        }
    }

    public interface ICommitteeRepository : IDisposable
    {
        IQueryable<Committee> All { get; }
        IQueryable<Committee> AllIncluding(params Expression<Func<Committee, object>>[] includeProperties);
        Committee Find(int id);
        void InsertOrUpdate(Committee committee, string currentUser);
        void Delete(int id);
        void Save();
    }
}