// <auto-generated />
namespace HickoryPTAApp.Migrations.ApplicationDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MemeberId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemeberId));
        
        string IMigrationMetadata.Id
        {
            get { return "201410101634051_MemeberId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
